name: job_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

# ----- PACKEGES ----- #

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  dio: ^5.3.0
  lottie: ^3.1.0
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  multi_select_flutter: ^4.1.3
  socket_io_client: ^2.0.3+1
  google_fonts: ^6.2.1

  # ----- ICON ----- #
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  get: ^4.6.5
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # ----- Local Assets ----- #
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/welcome/
    - assets/images/gif/
    - assets/images/company-logo/
    - assets/images/categories/
    - assets/images/banners/

  # fonts:
  #   - family: Overpass
  #     fonts:
  #       - asset: assets/fonts/Overpass-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Overpass-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Overpass-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Overpass-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Overpass-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets/fonts/Overpass-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Overpass-Bold.ttf
  #         weight: 800
